CREATE DATABASE IF NOT EXISTS energy_dw;
USE DATABASE energy_dw;

CREATE SCHEMA IF NOT EXISTS analytics;

CREATE WAREHOUSE IF NOT EXISTS energy_wh
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE energy_wh;
